### ISSUE TITLE
Add support for Markdown

### ISSUE THREAD

**Issue by mqnguyen5** [hlavu/my-ssg#13]
I suggest adding initial support for Markdown and would like to work on this feature.

I have created a list of the changes to be made to the code so you can have a look:

- [x] Modify `readFolder.js` to accept `.md` files.
- [x] Add a new `readMDFile.js` file to read the content of the `.md` files and generate their appropriate HTML body.
- [x] Add implementation to parse Markdown headings to their corresponding `<h1>` element.
- [x] Add implementation to parse Markdown link to their corresponding `<a>` element.
- [x] Update README.md to add documentation for Markdown support.

Reference for Markdown syntax can be found [here](https://commonmark.org/help/).

Let me know if there is anything I should be aware of before making these modifications or if there is a specific way that you want me to do them so I can work on it as soon as possible.

**Comment by hlavu** [comment]
That sounds good. Thanks.

**Comment by mqnguyen5** [comment]
I have finished most of the requirement on the list. Updates for README.md should be done by tomorrow.
