### ISSUE TITLE
Add new feature: Support --config with config file

### ISSUE THREAD

**Issue by tuanthanh2067** [hlavu/my-ssg#21]
Hello, I have an idea that you can add to your project. Basically, users are now able to pass url as parameters but in case they don't want to do it every time, so I'm thinking of adding a `config` option to your project, so that users just have to create a file and write their configuration to the file. 

Some config files for reference
```
  "input": "./docs"
```

```
{
  "input": "./docs",
  "output": "./web"
}
```

Task

- [x] The `-c` or `--config` flags accept a file path to a JSON config file.
- [x] If the file is missing, or can't be parsed as JSON, exit with an appropriate error message.
- [x] If the `-c` or `--config` option is provided, ignore all other options (i.e., a config file overrides other options on the command line).
- [x] The program should ignore any options in the config file it doesn't recognize. For example, if the SSG doesn't support stylesheets, ignore a stylesheet property.
- [x] If the config file is missing any options, assume the usual defaults. For example, use `dist/` as the `output` directory if it isn't specified.

**Comment by hlavu** [comment]
That sounds great.

**Comment by hlavu** [comment]
/@tuanthanh2067

**Comment by hlavu** [comment]
Close by [c23580](https://github.com/hlavu/my-ssg/commit/c235807b83779ae31d4eabd274e084d8a2e5e288)
