### ISSUE TITLE
Mismatch between descriptions in help and actual functionalities

### ISSUE THREAD

**Issue by minhhang107** [hlavu/my-ssg#4]
Options include -o but when tested with -o <folder>, HTML files are still generated inside dist folder

![issue](https://user-images.githubusercontent.com/55411709/133353593-b0e90315-5a01-4d31-8660-5e54700c806a.jpg)

**Comment by hlavu** [comment]
I set up the option first cause I want to apply this feature the next time. However, I forgot to comment that out. Thank you!
