### ISSUE TITLE
Modifications needed for readme file

### ISSUE THREAD

**Issue by minhhang107** [hlavu/my-ssg#5]
In general, the Readme file is pretty clear and I have some suggestions to improve the documentation:
- [x] Add installation details. 
Since I'm also using NodeJs, I can make a guess on how to install it, but others who are not familiar with NodeJs may need more instructions.
- [x] Use parallel structures in Features section (optional)
The documentation will look even more professional if the every feature description has the same structure (eg: full sentence and verb phrase etc.).

**Comment by hlavu** [comment]
Solved!
