### ISSUE TITLE
Unable to process file name / folder name with spaces

### ISSUE THREAD

**Issue by minhhang107** [hlavu/my-ssg#6]
The CLI is working well when the input is a name without spaces or when it's wrapped in quotation marks. However, the program can't find the file if there are spaces.
![issue3](https://user-images.githubusercontent.com/55411709/133367183-52308bde-156a-4cb1-8369-39c3d2d6608d.jpg)

The problem possibly starts when the program  checks for input path status.
![issue3-2](https://user-images.githubusercontent.com/55411709/133367233-5671e024-fded-4d97-bb2c-c83d82b92468.jpg)
When we do `node index.js -i a long file name.txt`, yargs only takes the 1st word as argv.input, that's why we got the ENOENT error so I believe you can start from there

**Comment by hlavu** [comment]
Solved!
