### ISSUE TITLE
Processing all file types in specified folder (should process .txt only)

### ISSUE THREAD

**Issue by minhhang107** [hlavu/my-ssg#7]
I created 2 files with different extensions in `testing` folder (file.doc and image.jpeg). When I specify `testing` as input, the CLI processes all files inside including .doc and .jpeg file.

![issue4](https://user-images.githubusercontent.com/55411709/133369606-8002c073-7ac0-4db1-b305-17f432a9d754.jpg)

I believe the issue's root lies in readFolder module and a quick filter will solve this.

**Comment by hlavu** [comment]
Solved!
